version: '3.1'

services:
  app:
    container_name: movies_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - movies-mysql
    networks:
      - fullstack

  movies-mysql:
    image: mysql:latest
    container_name: movies_db_mysql
    ports:
    - 3306:3306
    restart: on-failure
    environment:
      - MYSQL_ROOT_HOST=movies-mysql
      - MYSQL_USER=vitalis
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=movies
    networks:
      - fullstack
    volumes:
      - database_mysql:/var/lib/mysql

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge